SET FEEDBACK 1
SET NUMWIDTH 10
SET LINESIZE 150
SET TRIMSPOOL ON
SET TAB OFF
SET PAGESIZE 100

-- Users table

CREATE TABLE users (
    user_id       NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT user_id_nn NOT NULL
        CONSTRAINT user_id_pk PRIMARY KEY,
    full_name     VARCHAR(255)
        CONSTRAINT name_nn NOT NULL,
    email         VARCHAR(255)
        CONSTRAINT email_nn NOT NULL
        CONSTRAINT email_uk UNIQUE,
    password      VARCHAR(255)
        CONSTRAINT password_nn NOT NULL,
    phone         VARCHAR(10)
        CONSTRAINT phone_nn NOT NULL
        CONSTRAINT phone_uk UNIQUE,
    register_date DATE DEFAULT ( sysdate )
);

-- Locations table

CREATE TABLE locations (
    location_id          NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT location_id_nn NOT NULL
        CONSTRAINT location_id_pk PRIMARY KEY,
    user_id              NUMBER(10),
    department           VARCHAR(255)
        CONSTRAINT department_nn NOT NULL,
    city                 VARCHAR(255)
        CONSTRAINT city_nn NOT NULL,
    neighborhood         VARCHAR(255)
        CONSTRAINT neighborhood_nn NOT NULL,
    street_name          VARCHAR(255)
        CONSTRAINT street_name_nn NOT NULL,
    street_number        NUMBER(3)
        CONSTRAINT street_number_nn NOT NULL,
    second_street_number NUMBER(3)
        CONSTRAINT second_street_number_nn NOT NULL,
    third_street_number  NUMBER(3)
        CONSTRAINT third_street_number_nn NOT NULL,
    apartment            VARCHAR(255),
    additional_info      VARCHAR(1000),
    CONSTRAINT user_id_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id )
);

--  products table

CREATE TABLE products (
    product_id   NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT product_id_pk PRIMARY KEY,
    product_name VARCHAR(255)
        CONSTRAINT product_name_nn NOT NULL,
    description  VARCHAR(1000),
    price        NUMBER(10,2)
        CONSTRAINT price_nn NOT NULL,
    category     VARCHAR(50)
        CONSTRAINT category_nn NOT NULL,
    availability CHAR(1) CHECK ( availability IN ( 'Y', 'N' ) )
        CONSTRAINT availability_nn NOT NULL
);

--  orders table

CREATE TABLE orders (
    order_id   NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT order_id_pk PRIMARY KEY,
    user_id    NUMBER(10),
    order_date DATE
        CONSTRAINT order_date_nn NOT NULL,
    state      VARCHAR(50)
        CONSTRAINT state_nn NOT NULL,
    total      NUMBER(10, 2)
        CONSTRAINT total_nn NOT NULL,
    CONSTRAINT user_id_order_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id )
);

--  delivery men table

CREATE TABLE delivery_men (
    delivery_man_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT delivery_man_id_pk PRIMARY KEY,
    full_name VARCHAR(255)
        CONSTRAINT name_delivery_man_nn NOT NULL,
    phone VARCHAR(10)
        CONSTRAINT phone_delivery_man_nn NOT NULL
        CONSTRAINT phone_delivery_man_uk UNIQUE,
    vehicle VARCHAR(50)
        CONSTRAINT vehicle_nn NOT NULL 
);

--  deliveries table

CREATE TABLE deliveries (
    delivery_id     NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT delivery_id_pk PRIMARY KEY,
    order_id        NUMBER(10)
        CONSTRAINT order_id_delivery_nn NOT NULL,
    delivery_man_id NUMBER(10)
        CONSTRAINT delivery_man_id_nn NOT NULL,
    delivery_date   DATE
        CONSTRAINT delivery_date_nn NOT NULL,
    delivery_status VARCHAR(20)
        CONSTRAINT delivery_status_nn NOT NULL,
    CONSTRAINT order_id_delivery_fk FOREIGN KEY ( order_id )
        REFERENCES orders ( order_id )
);

--  offers table

CREATE TABLE offers (
    offer_id NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT offer_id_pk PRIMARY KEY,
    offer_name VARCHAR(255)
        CONSTRAINT name_offer_nn NOT NULL,
    description VARCHAR(1000),
    start_date DATE
        CONSTRAINT start_date_nn NOT NULL,
    end_date DATE
        CONSTRAINT end_date_nn NOT NULL,
    discount NUMBER
        CONSTRAINT discount_nn NOT NULL
);

--  order_products table

CREATE TABLE order_products (
    detail_id  NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT id_detail_pk PRIMARY KEY,
    order_id   NUMBER(10)
        CONSTRAINT id_order_nn NOT NULL,
    product_id NUMBER(10)
        CONSTRAINT id_product_nn NOT NULL,
    offer_id NUMBER(10),
    amount     NUMBER(10)
        CONSTRAINT amount_nn NOT NULL,
    unit_price NUMBER(10)
        CONSTRAINT unit_price_nn NOT NULL,
    CONSTRAINT order_id_fk FOREIGN KEY ( order_id )
        REFERENCES orders ( order_id ),
    CONSTRAINT product_id_fk FOREIGN KEY ( product_id )
        REFERENCES products ( product_id )
);

--  reviews table

CREATE TABLE reviews (
    review_id      NUMBER(10)
        GENERATED BY DEFAULT ON NULL AS IDENTITY
        CONSTRAINT review_id_pk PRIMARY KEY,
    user_id        NUMBER
        CONSTRAINT user_id_re_nn NOT NULL,
    product_id     NUMBER(10)
        CONSTRAINT product_id_re_nn NOT NULL,
    comment_review VARCHAR(1000),
    score          NUMBER(2)
        CONSTRAINT score_nn NOT NULL,
    CONSTRAINT user_id_review_fk FOREIGN KEY ( user_id )
        REFERENCES users ( user_id ),
    CONSTRAINT product_id_review_fk FOREIGN KEY ( product_id )
        REFERENCES products ( product_id )
);
